fix: handle constructors that are static anonymous functions
The `MethodObjectBuilder` was incorrectly used when a registered
constructor is a static anonymous functions — it was handled like a
static method closure `Class::method(...)` and would yield errors like
this:

Error: Call to undefined method stdClass::CuyZ\Valinor\Tests\Integration\Mapping\{closure}()

PHP Reflection does not provide any way of telling static functions and
closures of static methods apart, other than checking for the name
'{closure}'. We check that '{closure}' is actually the last part of the
fully-qualified name, instead of just checking that the string ends with
'{closure}'